nodeLinker: node-modules
npmRegistryServer: "https://ncrs-mfe-670422576278.d.codeartifact.eu-west-2.amazonaws.com/npm/nhsuk-react-components/"
npmAlwaysAuth: true
npmAuthToken: "${CODEARTIFACT_AUTH_TOKEN}"
